### ISSUE TITLE
"global name 'TextPastryHistory' is not defined"

### ISSUE THREAD

**Issue by slhck** [duydao/Text-Pastry#66]
I'm using Text Pastry with Sublime Build 3143 on macOS 10.12.

When I hit `super-alt-b`, I get this error in the Console:

```
command: text_pastry_redo
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "text_pastry in /Users/werner/Library/Application Support/Sublime Text 3/Installed Packages/Text Pastry.sublime-package", line 817, in run
NameError: global name 'TextPastryHistory' is not defined
```

(I would actually like to override this keyboard shortcut but when trying so I discovered this error.)

**Comment by duydao** [comment]
Thanks for reporting this & thanks for using Text Pastry!
